"""
Auto-generated Gov-Policy Multiplier matrix from policy_effects_complete.xlsx.

DO NOT EDIT MANUALLY. Re-generate with:
    ./backend/venv/Scripts/python.exe tools/import_from_excel.py

Structure: GOV_POLICY_MULTIPLIERS[gov_option_key][(category_key, level_index)] = float
Only non-1.0 entries are stored. Default is 1.0.
"""


GOV_POLICY_MULTIPLIERS = {
    'autarkic': {
        ('agricultural_subsidies', 0): 1.3,
        ('agricultural_subsidies', 1): 1.3,
        ('agricultural_subsidies', 2): 1.3,
        ('currency', 5): 0.4,
        ('emmigration_policy', 0): 1.3,
        ('immigration', 0): 1.3,
        ('immigration', 2): 0.6,
        ('immigration', 3): 0.4,
        ('resource_subsidies', 0): 1.3,
        ('resource_subsidies', 1): 1.3,
        ('resource_subsidies', 2): 1.3,
        ('visa_policy', 0): 1.3,
    },
    'bottom_up': {
        ('anti_corruption_policy', 0): 1.2,
        ('anti_corruption_policy', 1): 1.2,
        ('anti_corruption_policy', 2): 1.2,
        ('anti_corruption_policy', 3): 1.2,
        ('bureaucracy', 5): 1.3,
        ('bureaucracy', 6): 1.3,
        ('consumer_protections', 0): 1.2,
        ('consumer_protections', 1): 1.2,
        ('consumer_protections', 2): 1.2,
        ('consumer_protections', 3): 1.2,
        ('consumer_protections', 4): 1.2,
        ('domestic_intelligence_agency', 3): 0.5,
        ('freedom_of_association', 0): 1.3,
        ('freedom_of_association', 1): 0.7,
        ('freedom_of_press', 0): 0.5,
        ('freedom_of_press', 4): 1.3,
        ('freedom_of_speech', 0): 0.5,
        ('freedom_of_speech', 3): 1.3,
        ('martial_law', 0): 0.5,
        ('policing', 3): 1.2,
        ('policing', 4): 0.7,
        ('policing', 5): 0.6,
        ('suffrage', 0): 1.4,
        ('suffrage', 4): 0.5,
        ('unions', 0): 0.6,
        ('unions', 3): 1.3,
    },
    'collectivist': {
        ('firms', 1): 1.3,
        ('firms', 2): 1.4,
        ('firms', 3): 0.6,
        ('healthcare', 0): 0.6,
        ('healthcare', 2): 1.4,
        ('income_tax', 2): 0.5,
        ('income_tax', 3): 1.4,
        ('land_ownership', 2): 0.5,
        ('land_ownership', 4): 1.3,
        ('market', 0): 0.4,
        ('market', 2): 1.2,
        ('market', 3): 1.4,
        ('minimum_wage', 0): 1.3,
        ('minimum_wage', 1): 1.3,
        ('minimum_wage', 2): 0.5,
        ('pensions', 2): 1.3,
        ('property_rights', 0): 0.4,
        ('property_rights', 3): 1.3,
        ('unions', 0): 0.5,
        ('unions', 3): 1.3,
        ('working_hours', 0): 0.6,
        ('working_hours', 2): 1.2,
        ('working_hours', 3): 1.3,
    },
    'council': {
        ('anti_corruption_policy', 3): 1.2,
        ('bureaucracy', 7): 1.2,
        ('freedom_of_association', 0): 1.1,
        ('government_salary', 2): 1.1,
    },
    'direct': {
        ('domestic_intelligence_agency', 3): 0.5,
        ('freedom_of_association', 0): 1.3,
        ('freedom_of_speech', 0): 0.4,
        ('freedom_of_speech', 3): 1.4,
        ('policing', 5): 0.5,
        ('suffrage', 0): 1.5,
        ('suffrage', 4): 0.3,
    },
    'economic_success': {
        ('firm_size', 2): 1.3,
        ('firm_size', 3): 1.3,
        ('firms', 3): 1.3,
        ('industrial_subsidies', 0): 1.2,
        ('industrial_subsidies', 1): 1.2,
        ('industrial_subsidies', 2): 1.2,
        ('market', 0): 1.4,
        ('market', 3): 0.5,
        ('minimum_wage', 0): 0.7,
        ('minimum_wage', 3): 1.2,
        ('property_rights', 3): 0.3,
        ('suffrage', 0): 0.7,
        ('unions', 0): 1.2,
        ('unions', 3): 0.7,
    },
    'elections': {
        ('anti_corruption_policy', 0): 1.2,
        ('anti_corruption_policy', 1): 1.2,
        ('anti_corruption_policy', 2): 1.2,
        ('anti_corruption_policy', 3): 1.2,
        ('domestic_intelligence_agency', 3): 0.7,
        ('freedom_of_press', 0): 0.5,
        ('freedom_of_press', 4): 1.3,
        ('freedom_of_speech', 0): 0.5,
        ('freedom_of_speech', 3): 1.3,
        ('martial_law', 0): 0.5,
        ('policing', 5): 0.7,
        ('suffrage', 0): 1.5,
        ('suffrage', 4): 0.3,
    },
    'federal': {
        ('domestic_intelligence_agency', 3): 0.7,
        ('freedom_of_movement', 0): 1.2,
        ('land_tax', 0): 1.2,
        ('land_tax', 1): 1.2,
        ('land_tax', 2): 1.2,
        ('naturalization_laws', 0): 1.2,
        ('naturalization_laws', 1): 1.2,
        ('naturalization_laws', 2): 1.2,
        ('naturalization_laws', 3): 1.2,
        ('naturalization_laws', 4): 1.2,
        ('naturalization_laws', 5): 1.2,
        ('policing', 5): 0.8,
        ('visa_policy', 0): 1.2,
        ('visa_policy', 1): 1.2,
        ('visa_policy', 2): 1.2,
        ('visa_policy', 3): 1.2,
    },
    'hereditary': {
        ('anti_corruption_policy', 0): 0.8,
        ('anti_corruption_policy', 1): 0.8,
        ('anti_corruption_policy', 2): 0.8,
        ('anti_corruption_policy', 3): 0.8,
        ('bureaucracy', 3): 1.3,
        ('bureaucracy', 5): 0.5,
        ('bureaucracy', 6): 0.5,
        ('gender_roles', 0): 1.3,
        ('gender_roles', 3): 0.7,
        ('gift_and_estate_taxes', 1): 0.4,
        ('gift_and_estate_taxes', 2): 0.6,
        ('property_rights', 0): 1.2,
        ('racial_rights', 0): 1.2,
        ('social_discrimination', 0): 1.2,
        ('suffrage', 0): 0.4,
        ('suffrage', 4): 1.3,
    },
    'ideology': {
        ('domestic_intelligence_agency', 3): 1.3,
        ('education', 3): 1.3,
        ('educational_philosophy', 0): 1.3,
        ('educational_philosophy', 2): 1.2,
        ('freedom_of_association', 1): 1.3,
        ('freedom_of_press', 0): 1.4,
        ('freedom_of_press', 4): 0.5,
        ('freedom_of_speech', 0): 1.4,
        ('freedom_of_speech', 3): 0.5,
        ('policing', 4): 1.2,
        ('social_discrimination', 0): 1.2,
    },
    'large_body': {
        ('anti_corruption_policy', 2): 1.2,
        ('domestic_intelligence_agency', 3): 0.6,
        ('freedom_of_press', 4): 1.2,
        ('freedom_of_speech', 3): 1.2,
        ('martial_law', 0): 0.5,
        ('suffrage', 0): 1.2,
    },
    'law_and_order': {
        ('anti_corruption_policy', 0): 0.4,
        ('anti_corruption_policy', 1): 1.3,
        ('anti_corruption_policy', 2): 1.3,
        ('anti_corruption_policy', 3): 1.3,
        ('consumer_protections', 0): 1.2,
        ('consumer_protections', 1): 1.2,
        ('consumer_protections', 2): 1.2,
        ('consumer_protections', 3): 1.2,
        ('consumer_protections', 4): 1.2,
        ('drug_policy', 0): 0.6,
        ('drug_policy', 4): 1.3,
        ('health_and_safety_regulations', 0): 1.2,
        ('health_and_safety_regulations', 1): 1.2,
        ('health_and_safety_regulations', 2): 1.2,
        ('health_and_safety_regulations', 3): 1.2,
        ('health_and_safety_regulations', 4): 1.2,
        ('legal_system', 1): 1.3,
        ('legal_system', 3): 0.3,
        ('policing', 0): 0.3,
        ('policing', 3): 1.4,
        ('policing', 4): 1.3,
        ('prison_system', 0): 1.2,
        ('prison_system', 1): 1.2,
        ('prison_system', 2): 1.2,
        ('prison_system', 3): 1.2,
        ('prison_system', 4): 1.2,
        ('prison_system', 5): 1.2,
        ('prison_system', 6): 1.2,
        ('punishments', 0): 1.3,
        ('punishments', 1): 1.3,
        ('punishments', 2): 1.3,
        ('punishments', 3): 1.3,
        ('vice', 0): 0.7,
        ('vice', 4): 1.3,
    },
    'liberal': {
        ('agricultural_subsidies', 0): 0.7,
        ('agricultural_subsidies', 1): 0.7,
        ('agricultural_subsidies', 2): 0.7,
        ('firm_size', 2): 1.2,
        ('firm_size', 3): 1.3,
        ('firms', 1): 0.8,
        ('firms', 2): 0.5,
        ('firms', 3): 1.3,
        ('healthcare', 0): 1.3,
        ('healthcare', 2): 0.6,
        ('income_tax', 0): 1.2,
        ('income_tax', 1): 1.2,
        ('income_tax', 2): 1.2,
        ('income_tax', 3): 0.6,
        ('industrial_subsidies', 0): 0.7,
        ('industrial_subsidies', 1): 0.7,
        ('industrial_subsidies', 2): 0.7,
        ('market', 0): 1.5,
        ('market', 1): 1.3,
        ('market', 2): 0.7,
        ('market', 3): 0.4,
        ('minimum_wage', 0): 0.6,
        ('minimum_wage', 2): 1.2,
        ('minimum_wage', 3): 1.3,
        ('pensions', 2): 0.7,
        ('property_rights', 0): 1.4,
        ('property_rights', 3): 0.3,
        ('resource_subsidies', 0): 0.7,
        ('resource_subsidies', 1): 0.7,
        ('resource_subsidies', 2): 0.7,
        ('unions', 0): 1.2,
        ('unions', 3): 0.7,
    },
    'military_power': {
        ('civilian_firearm_ownership', 0): 1.3,
        ('freedom_of_association', 0): 0.5,
        ('freedom_of_association', 1): 1.3,
        ('freedom_of_press', 0): 1.3,
        ('freedom_of_press', 4): 0.5,
        ('martial_law', 0): 1.5,
        ('military_recruitment_standards', 0): 1.3,
        ('military_recruitment_standards', 1): 1.3,
        ('military_recruitment_standards', 2): 1.3,
        ('military_recruitment_standards', 3): 1.3,
        ('military_recruitment_standards', 4): 1.3,
        ('military_recruitment_standards', 5): 1.3,
        ('military_salaries', 0): 1.3,
        ('military_salaries', 1): 1.3,
        ('military_salaries', 2): 1.3,
        ('military_salaries', 3): 1.3,
        ('military_service', 0): 0.2,
        ('military_service', 1): 0.8,
        ('military_service', 2): 1.4,
        ('military_service', 3): 1.4,
        ('military_service', 4): 1.4,
        ('military_service', 5): 1.4,
        ('military_service', 6): 1.4,
        ('military_service', 7): 1.4,
        ('mobilization', 0): 0.6,
        ('mobilization', 1): 1.4,
        ('mobilization', 2): 1.4,
        ('mobilization', 3): 1.4,
        ('policing', 5): 1.3,
        ('suffrage', 0): 0.4,
        ('suffrage', 4): 1.3,
        ('unions', 0): 1.3,
        ('unions', 3): 0.5,
    },
    'multi_body': {
        ('anti_corruption_policy', 0): 0.5,
        ('anti_corruption_policy', 3): 1.4,
        ('consumer_protections', 4): 1.3,
        ('domestic_intelligence_agency', 3): 0.7,
        ('freedom_of_press', 4): 1.3,
        ('freedom_of_speech', 3): 1.2,
        ('martial_law', 0): 0.4,
        ('policing', 5): 0.7,
        ('suffrage', 0): 1.2,
    },
    'power_consensus': {
        ('anti_corruption_policy', 0): 1.1,
        ('anti_corruption_policy', 1): 1.1,
        ('anti_corruption_policy', 2): 1.1,
        ('anti_corruption_policy', 3): 1.1,
        ('freedom_of_association', 0): 1.2,
        ('unions', 3): 1.2,
    },
    'protectionist': {
        ('consumer_protections', 0): 1.2,
        ('consumer_protections', 1): 1.2,
        ('consumer_protections', 2): 1.2,
        ('consumer_protections', 3): 1.2,
        ('consumer_protections', 4): 1.2,
        ('immigration', 0): 1.3,
        ('immigration', 3): 0.6,
        ('industrial_subsidies', 0): 1.4,
        ('industrial_subsidies', 1): 1.4,
        ('industrial_subsidies', 2): 1.4,
        ('market', 0): 0.7,
        ('naturalization_laws', 0): 1.2,
        ('naturalization_laws', 1): 1.2,
        ('naturalization_laws', 2): 1.2,
        ('naturalization_laws', 3): 1.2,
        ('naturalization_laws', 4): 1.2,
        ('naturalization_laws', 5): 1.2,
        ('visa_policy', 0): 1.2,
        ('visa_policy', 1): 1.2,
        ('visa_policy', 2): 1.2,
        ('visa_policy', 3): 1.2,
    },
    'religious': {
        ('bureaucracy', 1): 1.5,
        ('drug_policy', 0): 0.4,
        ('drug_policy', 4): 1.4,
        ('drug_policy', 5): 1.5,
        ('educational_philosophy', 1): 1.4,
        ('educational_philosophy', 2): 0.5,
        ('family_planning', 2): 1.4,
        ('family_planning', 4): 0.7,
        ('family_planning', 5): 0.5,
        ('freedom_of_press', 4): 0.6,
        ('freedom_of_speech', 0): 1.3,
        ('freedom_of_speech', 3): 0.6,
        ('gender_rights', 0): 0.7,
        ('gender_rights', 3): 1.3,
        ('gender_roles', 0): 1.5,
        ('gender_roles', 3): 0.5,
        ('sexuality', 0): 1.4,
        ('sexuality', 3): 0.4,
        ('suffrage', 0): 0.6,
        ('vice', 0): 0.3,
        ('vice', 4): 1.4,
    },
    'representative': {
        ('anti_corruption_policy', 0): 1.2,
        ('anti_corruption_policy', 1): 1.2,
        ('anti_corruption_policy', 2): 1.2,
        ('anti_corruption_policy', 3): 1.2,
        ('consumer_protections', 0): 1.2,
        ('consumer_protections', 1): 1.2,
        ('consumer_protections', 2): 1.2,
        ('consumer_protections', 3): 1.2,
        ('consumer_protections', 4): 1.2,
        ('freedom_of_press', 0): 0.5,
        ('freedom_of_press', 4): 1.3,
        ('freedom_of_speech', 3): 1.2,
        ('suffrage', 0): 1.3,
        ('suffrage', 4): 0.3,
    },
    'resource': {
        ('conservation', 0): 1.3,
        ('conservation', 1): 1.3,
        ('conservation', 2): 1.3,
        ('conservation', 3): 1.3,
        ('conservation', 4): 1.3,
        ('industrial_subsidies', 0): 1.2,
        ('industrial_subsidies', 1): 1.2,
        ('industrial_subsidies', 2): 1.2,
        ('land_ownership', 0): 1.2,
        ('land_tax', 0): 1.2,
        ('land_tax', 1): 1.2,
        ('land_tax', 2): 1.2,
        ('resource_subsidies', 0): 1.5,
        ('resource_subsidies', 1): 1.5,
        ('resource_subsidies', 2): 1.5,
    },
    'singular': {
        ('anti_corruption_policy', 0): 1.3,
        ('anti_corruption_policy', 3): 0.4,
        ('bureaucracy', 6): 0.4,
        ('bureaucracy', 7): 1.4,
        ('domestic_intelligence_agency', 3): 1.4,
        ('foreign_intelligence_agency', 3): 1.3,
        ('freedom_of_press', 0): 1.4,
        ('freedom_of_press', 4): 0.4,
        ('freedom_of_speech', 3): 0.4,
        ('government_benefits', 0): 1.3,
        ('government_salary', 0): 1.3,
        ('martial_law', 0): 1.5,
        ('policing', 4): 1.3,
        ('policing', 5): 1.3,
        ('suffrage', 0): 0.3,
        ('suffrage', 4): 1.4,
        ('unions', 0): 1.3,
        ('unions', 3): 0.5,
    },
    'staggered_groups': {
        ('anti_corruption_policy', 0): 1.2,
        ('anti_corruption_policy', 1): 1.2,
        ('anti_corruption_policy', 2): 1.2,
        ('anti_corruption_policy', 3): 1.2,
        ('bureaucracy', 9): 1.2,
        ('legal_system', 1): 1.2,
        ('martial_law', 0): 0.6,
        ('suffrage', 0): 1.1,
    },
    'subsistence': {
        ('agricultural_subsidies', 0): 1.4,
        ('agricultural_subsidies', 1): 1.4,
        ('agricultural_subsidies', 2): 1.4,
        ('consumption_tax', 0): 0.7,
        ('consumption_tax', 1): 0.7,
        ('consumption_tax', 2): 0.7,
        ('consumption_tax', 3): 0.7,
        ('currency', 0): 0.6,
        ('education', 3): 0.5,
        ('firm_size', 2): 0.5,
        ('firm_size', 3): 0.4,
        ('healthcare', 2): 0.5,
        ('income_tax', 0): 0.7,
        ('income_tax', 1): 0.7,
        ('income_tax', 2): 0.7,
        ('income_tax', 3): 0.7,
        ('industrial_subsidies', 0): 0.7,
        ('industrial_subsidies', 1): 0.7,
        ('industrial_subsidies', 2): 0.7,
        ('market', 0): 0.7,
        ('market', 1): 0.8,
        ('market', 2): 0.8,
        ('market', 3): 0.8,
        ('market', 4): 0.8,
        ('pensions', 2): 0.5,
    },
    'top_down': {
        ('anti_corruption_policy', 0): 0.8,
        ('anti_corruption_policy', 1): 0.8,
        ('anti_corruption_policy', 2): 0.8,
        ('anti_corruption_policy', 3): 0.8,
        ('bureaucracy', 5): 0.5,
        ('bureaucracy', 6): 0.7,
        ('bureaucracy', 7): 1.3,
        ('consumer_protections', 0): 0.8,
        ('consumer_protections', 1): 0.8,
        ('consumer_protections', 2): 0.8,
        ('consumer_protections', 3): 0.8,
        ('consumer_protections', 4): 0.8,
        ('domestic_intelligence_agency', 0): 0.6,
        ('domestic_intelligence_agency', 1): 1.4,
        ('domestic_intelligence_agency', 2): 1.4,
        ('domestic_intelligence_agency', 3): 1.4,
        ('emmigration_policy', 0): 1.3,
        ('freedom_of_association', 0): 0.7,
        ('freedom_of_association', 1): 1.3,
        ('freedom_of_movement', 0): 0.7,
        ('freedom_of_movement', 1): 1.2,
        ('freedom_of_movement', 3): 1.3,
        ('freedom_of_press', 0): 1.4,
        ('freedom_of_press', 1): 1.3,
        ('freedom_of_press', 3): 0.8,
        ('freedom_of_press', 4): 0.6,
        ('freedom_of_speech', 0): 1.4,
        ('freedom_of_speech', 1): 1.2,
        ('freedom_of_speech', 3): 0.6,
        ('martial_law', 0): 1.4,
        ('policing', 0): 0.5,
        ('policing', 1): 1.3,
        ('policing', 2): 1.3,
        ('policing', 3): 1.3,
        ('policing', 4): 1.3,
        ('policing', 5): 1.3,
        ('suffrage', 0): 0.6,
        ('suffrage', 4): 1.3,
        ('unions', 0): 1.3,
        ('unions', 1): 0.7,
        ('unions', 2): 0.7,
        ('unions', 3): 0.7,
    },
}
