# Generated by Django 5.1.15 on 2026-03-19 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0001_initial'),
        ('nations', '0001_initial'),
        ('provinces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NationGoodStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumer_goods', models.FloatField(default=0)),
                ('arms', models.FloatField(default=0)),
                ('fuel', models.FloatField(default=0)),
                ('machinery', models.FloatField(default=0)),
                ('nation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='good_stocks', to='nations.nation')),
            ],
        ),
        migrations.CreateModel(
            name='NationResourcePool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.FloatField(default=0)),
                ('materials', models.FloatField(default=0)),
                ('energy', models.FloatField(default=0)),
                ('wealth', models.FloatField(default=0)),
                ('manpower', models.FloatField(default=0)),
                ('research', models.FloatField(default=0)),
                ('stability', models.FloatField(default=50.0)),
                ('total_population', models.PositiveIntegerField(default=0)),
                ('consecutive_food_deficit_turns', models.PositiveIntegerField(default=0)),
                ('nation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resource_pool', to='nations.nation')),
            ],
        ),
        migrations.CreateModel(
            name='TradeOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turn_number', models.PositiveIntegerField()),
                ('offering', models.JSONField(default=dict)),
                ('requesting', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('executed', 'Executed')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_nation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_trades', to='nations.nation')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_offers', to='games.game')),
                ('to_nation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_trades', to='nations.nation')),
            ],
        ),
        migrations.CreateModel(
            name='ProvinceLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turn_number', models.PositiveIntegerField()),
                ('population', models.PositiveIntegerField()),
                ('sector_allocations', models.JSONField(default=dict)),
                ('raw_production', models.JSONField(default=dict)),
                ('local_consumption', models.JSONField(default=dict)),
                ('exported_to_nation', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='provinces.province')),
            ],
            options={
                'ordering': ['-turn_number'],
                'unique_together': {('province', 'turn_number')},
            },
        ),
        migrations.CreateModel(
            name='ResourceLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turn_number', models.PositiveIntegerField()),
                ('province_production_total', models.JSONField(default=dict)),
                ('integration_losses', models.JSONField(default=dict)),
                ('national_modifier_effects', models.JSONField(default=dict)),
                ('trade_net', models.JSONField(default=dict)),
                ('consumption', models.JSONField(default=dict)),
                ('final_pools', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('nation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='nations.nation')),
            ],
            options={
                'ordering': ['-turn_number'],
                'unique_together': {('nation', 'turn_number')},
            },
        ),
    ]
