# Generated by Django 5.1.15 on 2026-03-19 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nationgoodstock',
            name='chemicals',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='nationgoodstock',
            name='components',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='nationgoodstock',
            name='heavy_equipment',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='nationgoodstock',
            name='medicine',
            field=models.FloatField(default=0),
        ),
    ]
