# Generated by Django 5.1.15 on 2026-03-20 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economy', '0002_add_new_goods_to_nationgoodstock'),
    ]

    operations = [
        migrations.AddField(
            model_name='nationgoodstock',
            name='military_goods',
            field=models.FloatField(default=0),
        ),
    ]
