# Generated by Django 5.1.15 on 2026-03-30 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economy', '0003_add_military_goods'),
    ]

    operations = [
        migrations.AddField(
            model_name='nationresourcepool',
            name='happiness',
            field=models.FloatField(default=50.0),
        ),
    ]
