# Generated by Django 5.1.15 on 2026-04-04 03:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economy', '0004_add_nation_happiness'),
        ('nations', '0003_gov_components'),
    ]

    operations = [
        migrations.AddField(
            model_name='nationresourcepool',
            name='literacy',
            field=models.FloatField(default=0.2),
        ),
        migrations.CreateModel(
            name='ResearchUnlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector', models.CharField(max_length=50)),
                ('tier', models.PositiveIntegerField(default=1)),
                ('unlocked_turn', models.PositiveIntegerField()),
                ('nation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_unlocks', to='nations.nation')),
            ],
            options={
                'unique_together': {('nation', 'sector')},
            },
        ),
    ]
