# Generated by Django 5.1.15 on 2026-04-13 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economy', '0006_remove_tradeoffer'),
        ('provinces', '0013_region_and_control'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlPoolSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turn_number', models.PositiveIntegerField()),
                ('tax_revenue_total', models.FloatField(default=0)),
                ('tax_revenue_retained', models.FloatField(default=0)),
                ('trade_capacity_total', models.FloatField(default=0)),
                ('trade_capacity_retained', models.FloatField(default=0)),
                ('bc_total', models.FloatField(default=0)),
                ('bc_retained', models.FloatField(default=0)),
                ('research_total', models.FloatField(default=0)),
                ('research_retained', models.FloatField(default=0)),
                ('province', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='control_snapshots', to='provinces.province')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='control_snapshots', to='provinces.region')),
            ],
            options={
                'ordering': ['-turn_number'],
            },
        ),
    ]
