# Generated by Django 5.1.15 on 2026-04-23 02:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economy', '0008_rename_wealth_kapital'),
        ('nations', '0007_treasury_and_market_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='nationresourcepool',
            name='treasury',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.CreateModel(
            name='NationMarketSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turn_number', models.PositiveIntegerField()),
                ('prices', models.JSONField(default=dict)),
                ('monthly_demand', models.JSONField(default=dict)),
                ('monthly_supply', models.JSONField(default=dict)),
                ('prev_subsistence_productivity', models.JSONField(default=dict)),
                ('shortage_factors', models.JSONField(default=dict)),
                ('nation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_snapshots', to='nations.nation')),
            ],
            options={
                'ordering': ['-turn_number'],
                'indexes': [models.Index(fields=['nation', '-turn_number'], name='economy_nat_nation__9b8b68_idx')],
                'unique_together': {('nation', 'turn_number')},
            },
        ),
    ]
