# Generated by Django 5.1.15 on 2026-03-19 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0001_initial'),
        ('nations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('terrain_type', models.CharField(choices=[('plains', 'Plains'), ('mountains', 'Mountains'), ('forest', 'Forest'), ('coast', 'Coast'), ('desert', 'Desert'), ('urban_ruins', 'Urban Ruins'), ('wasteland', 'Wasteland'), ('river_valley', 'River Valley')], max_length=20)),
                ('population', models.PositiveIntegerField(default=1000)),
                ('local_stability', models.FloatField(default=70.0)),
                ('is_capital', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provinces', to='games.game')),
                ('nation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provinces', to='nations.nation')),
            ],
        ),
        migrations.CreateModel(
            name='ProvinceResources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.FloatField(default=0)),
                ('materials', models.FloatField(default=0)),
                ('energy', models.FloatField(default=0)),
                ('wealth', models.FloatField(default=0)),
                ('manpower', models.FloatField(default=0)),
                ('research', models.FloatField(default=0)),
                ('updated_turn', models.PositiveIntegerField(default=0)),
                ('province', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='provinces.province')),
            ],
            options={
                'verbose_name_plural': 'Province resources',
            },
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_type', models.CharField(max_length=50)),
                ('level', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('under_construction', models.BooleanField(default=False)),
                ('construction_turns_remaining', models.PositiveIntegerField(default=0)),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buildings', to='provinces.province')),
            ],
            options={
                'unique_together': {('province', 'building_type')},
            },
        ),
        migrations.CreateModel(
            name='ProvinceSectorAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector', models.CharField(choices=[('agriculture', 'Agriculture'), ('industry', 'Industry'), ('energy', 'Energy'), ('commerce', 'Commerce'), ('military', 'Military'), ('research', 'Research')], max_length=20)),
                ('percentage', models.PositiveIntegerField()),
                ('turn_number', models.PositiveIntegerField()),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sector_allocations', to='provinces.province')),
            ],
            options={
                'unique_together': {('province', 'sector', 'turn_number')},
            },
        ),
    ]
