# Generated by Django 5.1.15 on 2026-03-19 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provinces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='province',
            name='designation',
            field=models.CharField(choices=[('rural', 'Rural'), ('urban', 'Urban'), ('post_urban', 'Post-Urban')], default='rural', max_length=20),
        ),
    ]
