# Generated by Django 5.1.15 on 2026-03-19 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provinces', '0002_add_province_designation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='province',
            name='designation',
            field=models.CharField(choices=[('rural', 'Rural'), ('urban', 'Urban'), ('post_urban', 'Post-Urban'), ('capital', 'Capital')], default='rural', max_length=20),
        ),
        migrations.AlterField(
            model_name='province',
            name='population',
            field=models.PositiveIntegerField(default=10000),
        ),
    ]
