# Generated by Django 5.1.15 on 2026-03-20 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nations', '0002_ideology_traits_and_policies'),
        ('provinces', '0003_capital_designation_and_pop_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='province',
            name='is_coastal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='province',
            name='is_river',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='MilitaryGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('nation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='military_groups', to='nations.nation')),
            ],
        ),
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('domain', models.CharField(choices=[('army', 'Army'), ('navy', 'Navy'), ('air', 'Air')], max_length=10)),
                ('formation_type', models.CharField(choices=[('reserve', 'Reserve'), ('active', 'Active')], default='reserve', max_length=10)),
                ('effective_strength', models.FloatField(default=0.0)),
                ('nation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formations', to='nations.nation')),
                ('province', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formations', to='provinces.province')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formations', to='provinces.militarygroup')),
            ],
        ),
        migrations.CreateModel(
            name='MilitaryUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_type', models.CharField(max_length=30)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('quantity_in_training', models.PositiveIntegerField(default=0)),
                ('construction_turns_remaining', models.FloatField(default=0.0)),
                ('is_active', models.BooleanField(default=True)),
                ('quantity_in_transit', models.PositiveIntegerField(default=0)),
                ('transit_turns_remaining', models.FloatField(default=0.0)),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='provinces.formation')),
                ('training_province', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='units_in_training', to='provinces.province')),
            ],
        ),
        migrations.AddConstraint(
            model_name='formation',
            constraint=models.UniqueConstraint(condition=models.Q(('formation_type', 'reserve')), fields=('nation', 'province', 'domain'), name='unique_reserve_formation_per_domain_province_nation'),
        ),
        migrations.AlterUniqueTogether(
            name='militaryunit',
            unique_together={('formation', 'unit_type')},
        ),
    ]
