# Generated by Django 5.1.15 on 2026-03-20 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
        ('provinces', '0004_add_coastal_river_and_military_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='province',
            name='adjacent_provinces',
            field=models.ManyToManyField(blank=True, db_table='provinces_province_adjacency', to='provinces.province'),
        ),
        migrations.AddField(
            model_name='province',
            name='center_x',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='province',
            name='center_y',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='province',
            name='river_border_distance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='province',
            name='sea_border_distance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='AirZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('adjacent_air_zones', models.ManyToManyField(blank=True, db_table='provinces_airzone_adjacency', to='provinces.airzone')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='air_zones', to='games.game')),
            ],
        ),
        migrations.AddField(
            model_name='province',
            name='air_zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provinces', to='provinces.airzone'),
        ),
        migrations.CreateModel(
            name='RiverZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('adjacent_air_zones', models.ManyToManyField(blank=True, db_table='provinces_riverzone_airzone', related_name='adjacent_river_zones', to='provinces.airzone')),
                ('adjacent_river_zones', models.ManyToManyField(blank=True, db_table='provinces_riverzone_adjacency', to='provinces.riverzone')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='river_zones', to='games.game')),
            ],
        ),
        migrations.AddField(
            model_name='province',
            name='adjacent_river_zones',
            field=models.ManyToManyField(blank=True, db_table='provinces_province_riverzone', related_name='adjacent_provinces', to='provinces.riverzone'),
        ),
        migrations.CreateModel(
            name='SeaZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('adjacent_air_zones', models.ManyToManyField(blank=True, db_table='provinces_seazone_airzone', related_name='adjacent_sea_zones', to='provinces.airzone')),
                ('adjacent_sea_zones', models.ManyToManyField(blank=True, db_table='provinces_seazone_adjacency', to='provinces.seazone')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sea_zones', to='games.game')),
            ],
        ),
        migrations.AddField(
            model_name='riverzone',
            name='sea_zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='river_zones', to='provinces.seazone'),
        ),
        migrations.AddField(
            model_name='province',
            name='adjacent_sea_zones',
            field=models.ManyToManyField(blank=True, db_table='provinces_province_seazone', related_name='adjacent_provinces', to='provinces.seazone'),
        ),
    ]
