# Generated by Django 5.1.15 on 2026-03-30 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provinces', '0005_zone_adjacency_and_travel'),
    ]

    operations = [
        migrations.AddField(
            model_name='province',
            name='local_security',
            field=models.FloatField(default=30.0),
        ),
    ]
