# Generated by Django 5.1.15 on 2026-03-30 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provinces', '0006_add_local_security'),
    ]

    operations = [
        migrations.AddField(
            model_name='province',
            name='local_happiness',
            field=models.FloatField(default=50.0),
        ),
    ]
