# Generated by Django 5.1.15 on 2026-04-04 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provinces', '0007_add_province_happiness'),
    ]

    operations = [
        migrations.AddField(
            model_name='province',
            name='literacy',
            field=models.FloatField(default=0.2),
        ),
    ]
