# Generated by Django 5.1.15 on 2026-04-12 02:23
# Data migration: seeds Province.relief from terrain_type using the canonical
# TERRAIN_TYPE_TO_RELIEF mapping from provinces.constants.

from django.db import migrations

TERRAIN_TYPE_TO_RELIEF = {
    "plains":      "flat",
    "mountains":   "mountainous",
    "forest":      "rugged",
    "coast":       "flat",
    "desert":      "flat",
    "urban_ruins": "flat",
    "wasteland":   "rugged",
    "river_valley": "marshy",
}


def seed_relief(apps, schema_editor):
    Province = apps.get_model("provinces", "Province")
    for terrain_type, relief in TERRAIN_TYPE_TO_RELIEF.items():
        Province.objects.filter(terrain_type=terrain_type).update(relief=relief)


def reverse_seed_relief(apps, schema_editor):
    # Reversing just resets to the field default ("flat"); data will be re-seeded
    # on re-apply.
    Province = apps.get_model("provinces", "Province")
    Province.objects.all().update(relief="flat")


class Migration(migrations.Migration):

    dependencies = [
        ('provinces', '0008_add_trade_province_fields'),
    ]

    operations = [
        migrations.RunPython(seed_relief, reverse_seed_relief),
    ]
