# Generated by Django 5.1.15 on 2026-04-04 04:11

import django.db.models.deletion
from django.db import migrations, models


def populate_core_province_ideology(apps, schema_editor):
    """
    For all existing provinces that belong to a nation, copy the nation's
    ideology_traits to the province and mark it as a core province.
    Provinces without a nation keep is_core=True (default) and empty ideology.
    """
    Province = apps.get_model("provinces", "Province")
    for province in Province.objects.select_related("nation").filter(nation__isnull=False):
        province.ideology_traits = province.nation.ideology_traits or {}
        province.original_nation = province.nation
        province.is_core = True
        province.save(update_fields=["ideology_traits", "original_nation", "is_core"])


class Migration(migrations.Migration):

    dependencies = [
        ('nations', '0003_gov_components'),
        ('provinces', '0008_add_province_literacy'),
    ]

    operations = [
        migrations.AddField(
            model_name='province',
            name='ideology_traits',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='province',
            name='is_core',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='province',
            name='normalization_duration',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='province',
            name='normalization_started_turn',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='province',
            name='original_nation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='original_provinces', to='nations.nation'),
        ),
        migrations.RunPython(
            populate_core_province_ideology,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
