# Generated by Django 5.1.15 on 2026-04-12 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provinces', '0009_provincial_integration'),
    ]

    operations = [
        migrations.AddField(
            model_name='province',
            name='relief',
            field=models.CharField(choices=[('flat', 'Flat'), ('hilly', 'Hilly'), ('rugged', 'Rugged'), ('marshy', 'Marshy'), ('mountainous', 'Mountainous')], default='flat', max_length=20),
        ),
        migrations.AddField(
            model_name='province',
            name='temperature_band',
            field=models.CharField(choices=[('mild', 'Mild'), ('hot', 'Hot'), ('cold', 'Cold')], default='mild', max_length=20),
        ),
        migrations.AddField(
            model_name='province',
            name='vegetation_level',
            field=models.CharField(choices=[('none', 'None'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=20),
        ),
    ]
