# Generated by Django 5.1.15 on 2026-04-13 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provinces', '0011_seed_relief_from_terrain'),
    ]

    operations = [
        migrations.AddField(
            model_name='province',
            name='deintegration_duration',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='province',
            name='deintegration_started_turn',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
