# Generated by Django 5.1.15 on 2026-04-19 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provinces', '0012_deintegration_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProvinceDevelopmentPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=30)),
                ('points', models.PositiveIntegerField(default=0)),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='development_points', to='provinces.province')),
            ],
            options={
                'unique_together': {('province', 'category')},
            },
        ),
    ]
