# Generated by Django 5.1.15 on 2026-04-13 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nations', '0005_region_and_control'),
        ('provinces', '0012_deintegration_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='province',
            name='control',
            field=models.FloatField(default=100.0),
        ),
        migrations.AddField(
            model_name='province',
            name='is_rebel_occupied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='province',
            name='rebel_timer_duration',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='province',
            name='rebel_timer_start_turn',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('control', models.FloatField(default=100.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('nation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='nations.nation')),
            ],
            options={
                'unique_together': {('nation', 'name')},
            },
        ),
        migrations.AddField(
            model_name='province',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provinces', to='provinces.region'),
        ),
    ]
