# Generated by Django 5.1.15 on 2026-03-19 18:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Nation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('government_type', models.CharField(max_length=30)),
                ('ideology', models.CharField(max_length=30)),
                ('motto', models.CharField(blank=True, max_length=200)),
                ('is_alive', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nations', to='games.game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('game', 'player')},
            },
        ),
        migrations.CreateModel(
            name='NationModifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('economy', 'Economy'), ('military', 'Military'), ('stability', 'Stability'), ('diplomacy', 'Diplomacy'), ('growth', 'Growth')], max_length=20)),
                ('target', models.CharField(max_length=50)),
                ('modifier_type', models.CharField(choices=[('flat', 'Flat'), ('percentage', 'Percentage')], max_length=15)),
                ('value', models.FloatField()),
                ('source', models.CharField(choices=[('government', 'Government'), ('ideology', 'Ideology'), ('event', 'Event'), ('policy', 'Policy'), ('trade', 'Trade')], max_length=20)),
                ('expires_turn', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('nation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modifiers', to='nations.nation')),
            ],
        ),
    ]
