# Generated by Django 5.1.15 on 2026-03-20 01:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nation',
            name='ideology',
        ),
        migrations.AddField(
            model_name='nation',
            name='ideology_traits',
            field=models.JSONField(default=dict, help_text='{"strong": "trait_key", "weak": ["trait_key", "trait_key"]}'),
        ),
        migrations.AlterField(
            model_name='nationmodifier',
            name='category',
            field=models.CharField(choices=[('economy', 'Economy'), ('military', 'Military'), ('stability', 'Stability'), ('diplomacy', 'Diplomacy'), ('growth', 'Growth'), ('building_efficiency', 'Building Efficiency')], max_length=20),
        ),
        migrations.AlterField(
            model_name='nationmodifier',
            name='source',
            field=models.CharField(choices=[('government', 'Government'), ('trait', 'Trait'), ('event', 'Event'), ('policy', 'Policy'), ('trade', 'Trade')], max_length=20),
        ),
        migrations.CreateModel(
            name='NationPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('level', models.PositiveSmallIntegerField()),
                ('changed_turn', models.PositiveIntegerField(blank=True, null=True)),
                ('nation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='nations.nation')),
            ],
            options={
                'unique_together': {('nation', 'category')},
            },
        ),
    ]
