# Generated by Django 5.1.15 on 2026-03-21 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nations", "0002_ideology_traits_and_policies"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="nation",
            name="government_type",
        ),
        migrations.AddField(
            model_name="nation",
            name="gov_direction",
            field=models.CharField(default="none", max_length=30),
        ),
        migrations.AddField(
            model_name="nation",
            name="gov_economic_category",
            field=models.CharField(default="subsistence", max_length=30),
        ),
        migrations.AddField(
            model_name="nation",
            name="gov_power_origin",
            field=models.CharField(default="law_and_order", max_length=30),
        ),
        migrations.AddField(
            model_name="nation",
            name="gov_power_type",
            field=models.CharField(default="council", max_length=30),
        ),
        migrations.AddField(
            model_name="nation",
            name="gov_structure",
            field=models.CharField(default="power_consensus", max_length=30),
        ),
    ]
