# Generated by Django 5.1.15 on 2026-04-12 02:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nations', '0003_gov_components'),
        ('provinces', '0011_seed_relief_from_terrain'),
    ]

    operations = [
        migrations.AddField(
            model_name='nation',
            name='capital_province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capital_of_nation', to='provinces.province'),
        ),
    ]
