# Generated by Django 5.1.15 on 2026-04-19 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nations', '0004_add_capital_province'),
    ]

    operations = [
        migrations.CreateModel(
            name='NationDPPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_points', models.PositiveIntegerField(default=0)),
                ('last_grant_turn', models.PositiveIntegerField(default=0)),
                ('nation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dp_pool', to='nations.nation')),
            ],
        ),
        migrations.CreateModel(
            name='NationMilitaryDP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20)),
                ('points', models.PositiveIntegerField(default=0)),
                ('nation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='military_dp', to='nations.nation')),
            ],
            options={
                'unique_together': {('nation', 'category')},
            },
        ),
    ]
