# Generated by Django 5.1.15 on 2026-04-13 14:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nations', '0004_add_capital_province'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='nation',
            name='is_npc',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='nation',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nations', to=settings.AUTH_USER_MODEL),
        ),
    ]
