# Generated by Django 5.1.15 on 2026-04-23 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nations', '0006_dp_pool_and_military'),
    ]

    operations = [
        migrations.AddField(
            model_name='nation',
            name='subsidies',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='nation',
            name='tax_rate',
            field=models.FloatField(default=0.15),
        ),
    ]
