# Generated by Django 5.1.15 on 2026-04-12 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0001_initial'),
        ('nations', '0004_add_capital_province'),
        ('provinces', '0011_seed_relief_from_terrain'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapitalRelocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_turn', models.PositiveIntegerField()),
                ('completes_turn', models.PositiveIntegerField()),
                ('cost_paid', models.JSONField(default=dict)),
                ('nation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='capital_relocation', to='nations.nation')),
                ('target_province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capital_relocations_targeting', to='provinces.province')),
            ],
        ),
        migrations.CreateModel(
            name='TradeRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good', models.CharField(max_length=50)),
                ('quantity_per_turn', models.PositiveIntegerField()),
                ('domain_mode', models.CharField(choices=[('multi', 'Multi-Domain'), ('land', 'Land Only'), ('sea', 'Sea Only'), ('air', 'Air Only')], default='multi', max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('inactive_war', 'Inactive (War)'), ('broken_path', 'Broken Path')], default='pending', max_length=20)),
                ('path_nodes', models.JSONField(default=list)),
                ('total_length', models.FloatField(default=0.0)),
                ('capacity_by_domain', models.JSONField(default=dict)),
                ('arrival_turns', models.PositiveIntegerField(default=1)),
                ('in_flight', models.JSONField(default=list)),
                ('created_turn', models.PositiveIntegerField()),
                ('from_nation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_trade_routes', to='nations.nation')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_routes', to='games.game')),
                ('to_nation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_trade_routes', to='nations.nation')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
