# Generated by Django 5.1.15 on 2026-04-01 02:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0001_initial'),
        ('nations', '0003_gov_components'),
        ('provinces', '0007_add_province_happiness'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchOfficeSpecialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(max_length=40)),
                ('building', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='espionage_specialization', to='provinces.building')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('action_type__in', ['investigate_province', 'promote_foreign_ideology', 'terrorist_attack', 'sabotage_building'])), name='branch_office_valid_specialization')],
            },
        ),
        migrations.CreateModel(
            name='EspionageAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('investigate_province', 'Investigate Province'), ('promote_foreign_ideology', 'Promote Foreign Ideology'), ('terrorist_attack', 'Terrorist Attack'), ('sabotage_building', 'Sabotage Building'), ('suppress_foreign_operations', 'Suppress Foreign Operations')], max_length=40)),
                ('target_building_type', models.CharField(blank=True, default='', max_length=60)),
                ('payload', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='active', max_length=12)),
                ('started_turn', models.PositiveIntegerField()),
                ('expires_turn', models.PositiveIntegerField(blank=True, null=True)),
                ('result', models.JSONField(default=dict)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.game')),
                ('nation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='espionage_actions', to='nations.nation')),
                ('target_nation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='espionage_actions_against', to='nations.nation')),
                ('target_province', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='provinces.province')),
            ],
            options={
                'indexes': [models.Index(fields=['game', 'nation', 'status'], name='espionage_e_game_id_6c9cac_idx')],
            },
        ),
        migrations.CreateModel(
            name='EspionageState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_attack', models.FloatField(default=0.0)),
                ('national_defense', models.FloatField(default=0.0)),
                ('transparency', models.FloatField(default=0.0)),
                ('revealed_info', models.JSONField(default=dict)),
                ('turn_updated', models.PositiveIntegerField(default=0)),
                ('attacker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='espionage_attacks', to='nations.nation')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='espionage_states', to='games.game')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='espionage_defenses', to='nations.nation')),
            ],
            options={
                'unique_together': {('game', 'attacker', 'target')},
            },
        ),
        migrations.CreateModel(
            name='IntelligenceSharing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('building_locations', 'Building Locations'), ('province_level_info', 'Province Level Info'), ('positions_of_formations', 'Positions Of Formations'), ('cointel', 'Cointel'), ('foreign_espionage', 'Foreign Espionage')], max_length=30)),
                ('is_shared', models.BooleanField(default=False)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.game')),
                ('source_nation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intelligence_shared_out', to='nations.nation')),
                ('viewer_nation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intelligence_shared_in', to='nations.nation')),
            ],
            options={
                'unique_together': {('game', 'source_nation', 'viewer_nation', 'category')},
            },
        ),
    ]
