"""
Build economy/happiness_policy_data.py from trait_policy_matrix.xlsx.

Reads the Trait-Policy Matrix sheet, matches rows to POLICY_CATEGORIES by name,
and writes the HAPPINESS_POLICY_MATRIX dict.

Run from the backend/ directory:
    cd backend
    DJANGO_SETTINGS_MODULE=phoenix_epoch.settings.dev ./venv/Scripts/python.exe ../tools/build_happiness_matrix.py
"""

import sys, os
sys.stdout.reconfigure(encoding="utf-8")

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BACKEND_DIR = os.path.join(ROOT, "backend")
XLSX_PATH = os.path.join(ROOT, "trait_policy_matrix.xlsx")
OUTPUT_PATH = os.path.join(ROOT, "backend", "economy", "happiness_policy_data.py")

if BACKEND_DIR not in sys.path:
    sys.path.insert(0, BACKEND_DIR)

import django
django.setup()

import openpyxl
from nations.policy_constants import POLICY_CATEGORIES

# ---------------------------------------------------------------------------
# Load xlsx
# ---------------------------------------------------------------------------
wb = openpyxl.load_workbook(XLSX_PATH, data_only=True)
ws = wb["Trait-Policy Matrix"]

rows = list(ws.iter_rows(values_only=True))
header = rows[0]

# Trait columns: indices 2-19 (after Category and Policy Option)
TRAIT_HEADERS = [str(h).lower() if h else "" for h in header[2:]]

# ---------------------------------------------------------------------------
# Build lookup: normalised name → policy_key
# ---------------------------------------------------------------------------
def normalise(s):
    return str(s).strip().lower() if s else ""

cat_name_to_key = {normalise(v["name"]): k for k, v in POLICY_CATEGORIES.items()}

# Build level lookup: policy_key → {normalised_level_name: level_index}
level_lookup = {}
for key, cat in POLICY_CATEGORIES.items():
    level_lookup[key] = {normalise(lv["name"]): i for i, lv in enumerate(cat["levels"])}

# ---------------------------------------------------------------------------
# Parse rows into matrix
# ---------------------------------------------------------------------------
matrix = {}  # policy_key → {level_index → {trait_key: score}}

current_cat_key = None
skipped_cats = set()
skipped_levels = []

for row in rows[1:]:
    category_cell, option_name, *trait_scores = row

    if category_cell is not None:
        cat_norm = normalise(category_cell)
        current_cat_key = cat_name_to_key.get(cat_norm)
        if current_cat_key is None:
            skipped_cats.add(str(category_cell))

    if current_cat_key is None or option_name is None:
        continue

    level_name = normalise(option_name)
    level_index = level_lookup.get(current_cat_key, {}).get(level_name)
    if level_index is None:
        skipped_levels.append(f"{current_cat_key} / {option_name}")
        continue

    scores = {}
    for trait_key, score in zip(TRAIT_HEADERS, trait_scores):
        if not trait_key:
            continue
        # 'D' = disabled (policy ban, not a happiness score) → treat as 0
        if score == "D" or score is None or score == 0:
            continue
        scores[trait_key] = int(score)

    if scores:
        if current_cat_key not in matrix:
            matrix[current_cat_key] = {}
        matrix[current_cat_key][level_index] = scores

# ---------------------------------------------------------------------------
# Diagnostics
# ---------------------------------------------------------------------------
if skipped_cats:
    print(f"[WARN] Unmatched categories ({len(skipped_cats)}): {sorted(skipped_cats)}")
if skipped_levels:
    print(f"[WARN] Unmatched levels ({len(skipped_levels)}):")
    for s in skipped_levels:
        print(f"  {s}")

matched_cats = len(matrix)
total_entries = sum(len(levels) for levels in matrix.values())
print(f"[OK] Matched {matched_cats} categories, {total_entries} policy-level entries with non-zero scores.")

# ---------------------------------------------------------------------------
# Write output
# ---------------------------------------------------------------------------
lines = [
    '"""',
    'Happiness policy matrix — generated by tools/build_happiness_matrix.py.',
    '',
    'HAPPINESS_POLICY_MATRIX[policy_category_key][level_index] = {trait_key: score}',
    '',
    'Scores: -3 (hard opposed) to +3 (core expression). Only non-zero entries stored.',
    '"D" values (policy bans) are omitted — handled by POLICY_REQUIREMENTS/BANS.',
    '"""',
    '',
    'HAPPINESS_POLICY_MATRIX = {',
]

for cat_key in sorted(matrix.keys()):
    lines.append(f'    "{cat_key}": {{')
    for level_index in sorted(matrix[cat_key].keys()):
        scores = matrix[cat_key][level_index]
        score_str = ", ".join(f'"{t}": {v}' for t, v in sorted(scores.items()))
        lines.append(f'        {level_index}: {{{score_str}}},')
    lines.append('    },')

lines.append('}')
lines.append('')

with open(OUTPUT_PATH, "w", encoding="utf-8") as f:
    f.write("\n".join(lines))

print(f"[OK] Written to {OUTPUT_PATH}")
