# Generated by Django 5.1.15 on 2026-03-20 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0001_initial'),
        ('nations', '0002_ideology_traits_and_policies'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turn_number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=12)),
                ('deadline', models.DateTimeField()),
                ('resolution_log', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='games.game')),
            ],
            options={
                'ordering': ['-turn_number'],
                'unique_together': {('game', 'turn_number')},
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.CharField(choices=[('set_allocation', 'Set Allocation'), ('trade_offer', 'Trade Offer'), ('trade_response', 'Trade Response'), ('policy_change', 'Policy Change'), ('build_improvement', 'Build Improvement'), ('train_unit', 'Train Unit'), ('create_formation', 'Create Formation'), ('assign_to_formation', 'Assign To Formation'), ('rename_formation', 'Rename Formation'), ('create_group', 'Create Group'), ('rename_group', 'Rename Group'), ('assign_formation_to_group', 'Assign Formation To Group')], max_length=30)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('validated', 'Validated'), ('executed', 'Executed'), ('failed', 'Failed')], default='draft', max_length=12)),
                ('payload', models.JSONField(default=dict)),
                ('validation_errors', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='nations.nation')),
                ('turn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='turns.turn')),
            ],
        ),
        migrations.CreateModel(
            name='TurnSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('nation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='nations.nation')),
                ('turn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='turns.turn')),
            ],
            options={
                'unique_together': {('turn', 'nation')},
            },
        ),
    ]
